<?php
/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
//include_once $GLOBALS['THRIFT_ROOT'].'/Thrift.php';


$GLOBALS['E_AnnotationType'] = array(
  'BOOL' => 0,
  'BYTES' => 1,
  'I16' => 2,
  'I32' => 3,
  'I64' => 4,
  'DOUBLE' => 5,
  'STRING' => 6,
);

final class AnnotationType {
  const BOOL = 0;
  const BYTES = 1;
  const I16 = 2;
  const I32 = 3;
  const I64 = 4;
  const DOUBLE = 5;
  const STRING = 6;
  static public $__names = array(
    0 => 'BOOL',
    1 => 'BYTES',
    2 => 'I16',
    3 => 'I32',
    4 => 'I64',
    5 => 'DOUBLE',
    6 => 'STRING',
  );
}

class Endpoint {
  static $_SPEC;

  public $ipv4 = null;
  public $port = null;
  public $serviceName = null;

  public function __construct($vals=null) {
    if (is_array($vals)) {
      if (isset($vals['ipv4'])) {
        $this->ipv4 = $vals['ipv4'];
      }
      if (isset($vals['port'])) {
        $this->port = $vals['port'];
      }
      if (isset($vals['serviceName'])) {
        $this->serviceName = $vals['serviceName'];
      }
    }
  }
}

class Annotation {
  static $_TSPEC;

  public $timestamp = null;
  public $value = null;
  public $endpoint = null;
  //public $duration = null;

  public function __construct($vals=null) {
    if (is_array($vals)) {
      if (isset($vals['timestamp'])) {
        $this->timestamp = $vals['timestamp'];
      }
      if (isset($vals['value'])) {
        $this->value = $vals['value'];
      }
      if (isset($vals['endpoint'])) {
        $this->endpoint = $vals['endpoint'];
      }
      if (isset($vals['duration'])) {
        $this->duration = $vals['duration'];
      }
    }
  }
}

class BinaryAnnotation {
  static $_TSPEC;

  public $key = null;
  public $value = null;
  public $annotation_type = null;
  public $endpoint = null;

  public function __construct($vals=null) {
    if (is_array($vals)) {
      if (isset($vals['key'])) {
        $this->key = $vals['key'];
      }
      if (isset($vals['value'])) {
        $this->value = $vals['value'];
      }
      if (isset($vals['annotation_type'])) {
        $this->annotation_type = $vals['annotation_type'];
      }
      if (isset($vals['endpoint'])) {
        $this->endpoint = $vals['endpoint'];
      }
    }
  }

}

class Span {
  static $_TSPEC;

  public $traceId = null;
  public $name = null;
  public $id = null;
  public $parentId = null;
  public $annotations = null;
  public $binaryAnnotations = null;
  public $debug = false;

  public function __construct($vals=null) {
    if (is_array($vals)) {
      if (isset($vals['traceId'])) {
        $this->traceId = $vals['traceId'];
      }
      if (isset($vals['name'])) {
        $this->name = $vals['name'];
      }
      if (isset($vals['id'])) {
        $this->id = $vals['id'];
      }
      if (isset($vals['parentId'])) {
        $this->parentId = $vals['parentId'];
      }
      if (isset($vals['annotations'])) {
        $this->annotations = $vals['annotations'];
      }
      if (isset($vals['binaryAnnotations'])) {
        $this->binaryAnnotations = $vals['binaryAnnotations'];
      }
      if (isset($vals['debug'])) {
        $this->debug = $vals['debug'];
      }
    }
  }

}

?>
